# Generated by Django 3.0.4 on 2020-04-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('nb_reserved', models.IntegerField(default=0)),
                ('nb_available', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CartProcutOrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.ProductORM')),
            ],
        ),
    ]
