# Generated by Django 3.0.4 on 2020-04-03 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
                ('task_status', models.IntegerField(choices=[(0, 'UNDONE'), (1, 'DONE')])),
                ('postpone_count', models.IntegerField()),
            ],
        ),
    ]
